# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Layers' do

pod 'ObjectMapper', '~> 1.4'
pod 'KeychainAccess', '~> 2.3'
pod 'SDWebImage', '~> 3.8'
pod 'Alamofire', '~> 3.4'
pod 'SwiftyJSON', '~> 2.3'
pod 'SwiftyBeaver', '~> 0.6'
pod 'FBSDKCoreKit', '~> 4.11'
pod 'FBSDKLoginKit', '~> 4.11'
pod 'UITextView+Placeholder', '~> 1.2'
pod 'AWSCore', '~> 2.4'
pod 'AWSCognito', '~> 2.4'
pod 'AWSCognitoIdentityProvider', '~> 2.4'
pod 'AWSSNS', '~> 2.4'
pod 'MBProgressHUD', '~> 1.0'
pod 'DeepLinkKit', '~> 1.2'
pod 'SwiftRangeSlider', '~> 0.3'
pod 'NHAlignmentFlowLayout', '~> 0.1'
pod 'Fabric', '~> 1.6'
pod 'Crashlytics', '~> 3.7'
pod 'IDMPhotoBrowser', '~> 1.8'
pod 'KLCPopup', '~> 1.0'
pod 'FRHyperLabel', '~> 1.0'
pod 'DateTools', '~> 1.7'
pod 'SwiftyTimer', '~> 1.4'
pod 'DominantColor', :git => 'https://github.com/indragiek/DominantColor.git'

end

