# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Layers' do

pod 'ObjectMapper'
pod 'KeychainAccess'
pod 'SDWebImage'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'HidingNavigationBar', '~> 0.3'
pod 'Cosmos', '~> 1.2'
pod 'SwiftyBeaver'
pod 'HMSegmentedControl'
pod 'Charts'
pod 'FBSDKCoreKit', '~> 4.11'
pod 'FBSDKLoginKit', '~> 4.11'

end

